# Generic work-developer Windows box.
# Run from a normal (non-admin) PowerShell after Git is available, or let
# this script install Git + Windows Terminal via winget.
#
#   powershell -ExecutionPolicy Bypass -File .\windows\work-setup.ps1
#
# Personal NAS maps and machine-specific PATH live in user-setup.ps1 /
# initial-admin-setup.ps1 and are not used here.

$ErrorActionPreference = "Stop"

function Test-IsAdmin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($id)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Install-WingetPackage([string]$Id) {
    Write-Host "==> winget install $Id"
    winget install --id $Id -e --accept-source-agreements --accept-package-agreements
}

if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    Write-Error "winget is required. Install App Installer from the Microsoft Store first."
}

Install-WingetPackage "Microsoft.WindowsTerminal"
Install-WingetPackage "Git.Git"
Install-WingetPackage "JanDeDobbeleer.OhMyPosh"

$repo = Join-Path $HOME "dot-files"
if (-not (Test-Path (Join-Path $repo ".git"))) {
    Write-Host "==> clone dot-files into $repo"
    git clone "https://github.com/DragonCrafted87/dot-files.git" $repo
}

$settingsSrc = Join-Path $repo "windows\terminal-settings.json"
$settingsTargets = @(
    (Join-Path $env:LOCALAPPDATA "Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"),
    (Join-Path $env:LOCALAPPDATA "Microsoft\Windows Terminal\settings.json")
)
foreach ($dest in $settingsTargets) {
    $dir = Split-Path $dest -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    Write-Host "==> copy terminal settings -> $dest"
    Copy-Item -Force $settingsSrc $dest
}

$stub = @"
# Generated by windows/work-setup.ps1
export GIT_BASH=true
# shellcheck disable=SC1091
source "`$HOME/dot-files/git_bashrc.sh"
"@
foreach ($name in @(".bashrc", ".bash_profile")) {
    $path = Join-Path $HOME $name
    Write-Host "==> write $path"
    Set-Content -Path $path -Value $stub -Encoding utf8
}

if (Test-IsAdmin) {
    Write-Host "warning: this script does not need admin; finish any remaining user-level setup without elevation"
}

Write-Host "==> done"
Write-Host "    open Windows Terminal; the default profile is Git Bash"
Write-Host "    first launch of Git Bash will source ~/dot-files/git_bashrc.sh"
