################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

# Fallback if a display is not listed below
monitor=,preferred,auto,auto

# Triple-head layout (left → ultrawide → right)
monitor=DP-2,2560x1440@143.91,0x0,1
monitor=DP-3,3440x1440@144,2560x0,1
monitor=HDMI-A-1,2560x1440@143.91Hz,6000x0,1
