###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = /usr/lib/pam_kwallet_init
exec-once = qdbus6 org.kde.kwalletd6 /modules/kwalletd6 org.kde.KWallet.open kdewallet 0 login

exec-once = hypridle

exec-once = $terminal
exec-once = brave-browser
#exec-once = /var/lib/flatpak/app/com.discordapp.Discord/current/active/export/bin/com.discordapp.Discord
#exec-once = steam
#exec-once = code

exec-once = systemctl --user start hyprpolkitagent
exec-once = ~/.config/hypr/scripts/startup_minimized.sh

#launcher
exec-once = /home/dragon/.config/hypr/scripts/startmenu.sh

# Keep the active border gradient spinning (0.48 loop workaround)
exec-once = ~/.config/hypr/scripts/spin-border.sh
