##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/0.48.0/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/0.48.0/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


xwayland {
    enabled = true
}


# Guild Wars – span all three monitors
windowrulev2 = float, class:^(Gw\.exe)$
windowrulev2 = size 8560 1440, class:^(Gw\.exe)$
windowrulev2 = move 0 0, class:^(Gw\.exe)$
windowrulev2 = center, class:^(Gw\.exe)$          # optional safety
windowrulev2 = pin, class:^(Gw\.exe)$             # stays on top of workspaces if you want
windowrulev2 = noanim, class:^(Gw\.exe)$
windowrulev2 = noblur, class:^(Gw\.exe)$
windowrulev2 = noborder, class:^(Gw\.exe)$
windowrulev2 = noshadow, class:^(Gw\.exe)$
windowrulev2 = rounding 0, class:^(Gw\.exe)$
windowrulev2 = suppressevent maximize fullscreen, class:^(Gw\.exe)$


# cursor {
#     no_hardware_cursors = true
# }
