general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/scripts/idle-display-on.sh
    ignore_dbus_inhibit = false
}

# Blank
listener {
    timeout = 420
    on-timeout = ~/.config/hypr/scripts/idle-display-off.sh
    on-resume = ~/.config/hypr/scripts/idle-display-on.sh
}

# Lock
listener {
    timeout = 900
    on-timeout = pidof hyprlock || hyprlock
}
