# Refer to the wiki for more information.
# https://wiki.hypr.land/0.48.0/Configuring/

source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/programs-autostart.conf
source = ~/.config/hypr/conf.d/look-and-feel.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/window-rules.conf
