#!/usr/bin/env python3
# pylint: disable=invalid-name
"""Write hyprsunset.conf from today's local sunrise and sunset.

hyprsunset v0.4.0 only accepts clock times. This generator fills those
clocks from the built-in coordinates. A host file can override both
with SUN_LAT and SUN_LON in conf.d/hosts.d/<host>.conf.

When upstream hyprsunset accepts time = sunrise, delete this script,
hyprsunset-times.service, and hyprsunset-times.timer, and put latitude
and longitude in the config instead.
"""

import math
import socket
import subprocess
import sys
from datetime import datetime
from datetime import timedelta
from datetime import timezone
from pathlib import Path

NIGHT_TEMPERATURE = 4500
STALE_AFTER = timedelta(days=7)
ZENITH = 90.833
# Desk location. Laptops can set SUN_LAT and SUN_LON on their host file later.
DEFAULT_LATITUDE = 38.0892644
DEFAULT_LONGITUDE = -92.4954407


def sun_clocks(latitude, longitude, day, tzinfo):
    """Return local HH:MM sunrise and sunset, or None when the sun does not cross the zenith."""
    rise = _solar_event(latitude, longitude, day, tzinfo, rising=True)
    sett = _solar_event(latitude, longitude, day, tzinfo, rising=False)
    if rise is None or sett is None:
        return None
    return rise.strftime("%H:%M"), sett.strftime("%H:%M")


def _solar_event(latitude, longitude, day, tzinfo, rising):
    # NOAA solar calculator (official zenith 90.833 degrees).
    day_of_year = day.timetuple().tm_yday
    lng_hour = longitude / 15.0
    approx = day_of_year + ((6.0 if rising else 18.0) - lng_hour) / 24.0
    mean_anomaly = (0.9856 * approx) - 3.289
    true_long = (
        mean_anomaly
        + (1.916 * math.sin(math.radians(mean_anomaly)))
        + (0.020 * math.sin(math.radians(2 * mean_anomaly)))
        + 282.634
    ) % 360.0
    right_asc = (
        math.degrees(math.atan(0.91764 * math.tan(math.radians(true_long)))) % 360.0
    )
    right_asc = right_asc + (
        math.floor(true_long / 90.0) * 90.0 - math.floor(right_asc / 90.0) * 90.0
    )
    right_asc /= 15.0
    sin_dec = 0.39782 * math.sin(math.radians(true_long))
    cos_dec = math.cos(math.asin(sin_dec))
    cos_hour = (
        math.cos(math.radians(ZENITH)) - (sin_dec * math.sin(math.radians(latitude)))
    ) / (cos_dec * math.cos(math.radians(latitude)))
    if cos_hour > 1 or cos_hour < -1:
        return None
    hour_angle = math.degrees(math.acos(cos_hour))
    if rising:
        hour_angle = 360.0 - hour_angle
    hour_angle /= 15.0
    local_mean = hour_angle + right_asc - (0.06571 * approx) - 6.622
    utc_hours = (local_mean - lng_hour) % 24.0
    utc_midnight = datetime(day.year, day.month, day.day, tzinfo=timezone.utc)
    local = (utc_midnight + timedelta(hours=utc_hours)).astimezone(tzinfo)
    # The hour-of-day is right; the UTC wrap can land on the neighboring date.
    return local + timedelta(days=(day - local.date()).days)


def host_conf_path():
    host = socket.gethostname().split(".", 1)[0]
    return Path.home() / ".config" / "hypr" / "conf.d" / "hosts.d" / f"{host}.conf"


def read_coords(path):
    latitude = None
    longitude = None
    if not path.is_file():
        return None, None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not value:
            continue
        if key == "SUN_LAT":
            latitude = float(value)
        elif key == "SUN_LON":
            longitude = float(value)
    return latitude, longitude


def config_text(sunrise, sunset, day):
    return (
        "# Generated by hyprsunset-times.py. Do not edit.\n"
        f"# day = {day.isoformat()}\n"
        "max-gamma = 100\n"
        "\n"
        "profile {\n"
        f"    time = {sunrise}\n"
        "    identity = true\n"
        "}\n"
        "\n"
        "profile {\n"
        f"    time = {sunset}\n"
        f"    temperature = {NIGHT_TEMPERATURE}\n"
        "}\n"
    )


def config_path():
    return Path.home() / ".config" / "hypr" / "hyprsunset.conf"


def session_active():
    result = subprocess.run(
        ["systemctl", "--user", "is-active", "--quiet", "graphical-session.target"],
        check=False,
    )
    return result.returncode == 0


def enable_and_maybe_restart(changed):
    subprocess.run(["systemctl", "--user", "enable", "hyprsunset.service"], check=False)
    if changed and session_active():
        subprocess.run(
            ["systemctl", "--user", "restart", "hyprsunset.service"], check=False
        )


def resolve_coords():
    latitude, longitude = read_coords(host_conf_path())
    if latitude is None or longitude is None:
        return DEFAULT_LATITUDE, DEFAULT_LONGITUDE
    return latitude, longitude


def apply_times():
    latitude, longitude = resolve_coords()
    now = datetime.now().astimezone()
    clocks = sun_clocks(latitude, longitude, now.date(), now.tzinfo)
    if clocks is None:
        print("hyprsunset-times: no sunrise or sunset for this date", file=sys.stderr)
        return 0
    sunrise, sunset = clocks
    text = config_text(sunrise, sunset, now.date())
    dest = config_path()
    changed = not dest.is_file() or dest.read_text(encoding="utf-8") != text
    if changed:
        dest.write_text(text, encoding="utf-8")
        print(f"hyprsunset-times: {sunrise} identity, {sunset} {NIGHT_TEMPERATURE}K")
    enable_and_maybe_restart(changed)
    return 0


def refresh_if_stale():
    dest = config_path()
    if dest.is_file():
        age = (
            datetime.now().astimezone()
            - datetime.fromtimestamp(dest.stat().st_mtime).astimezone()
        )
        if age < STALE_AFTER:
            return 0
    return apply_times()


def self_check():
    # New York, 2024-06-21. Eastern daylight is UTC-4. Official sunrise is 05:25.
    eastern = timezone(timedelta(hours=-4))
    clocks = sun_clocks(40.7128, -74.0060, datetime(2024, 6, 21).date(), eastern)
    if clocks != ("05:25", "20:30"):
        print(f"hyprsunset-times: self-check got {clocks}", file=sys.stderr)
        return 1
    print("hyprsunset-times: self-check ok")
    return 0


def main(argv):
    command = argv[1] if len(argv) > 1 else "apply"
    if command == "apply":
        return apply_times()
    if command == "refresh":
        return refresh_if_stale()
    if command == "self-check":
        return self_check()
    print("Usage: hyprsunset-times.py apply|refresh|self-check", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
